### PR TITLE
Avoid using AddOnSkins, fix border issue

### PR DESCRIPTION
**Pull request by Meivyn**
These changes are intended to avoid using AddOnSkins, so the skin is more consistent with ElvUI's "actual" style, unlike AddOnSkins.

I have also an annoying issue with borders of items without a border that takes a random green/blue/purple border when items in bags are moving, and can't be fixed without a reload. This seems to fix it.

### CODE REVIEW

**Comment by Klixxx** [comment]
No net the whole day, ill look at it tomorrow i like your idea of ditching AddOnSkins dependencies! And fix that border issue at the same time
Thanks!

**Comment by Meivyn** [comment]
It looks like the whole border thing is broken, I have also issues with junk items. Some items are dimmed even if they're not junk.
I'll look for a fix instead of a "workaround" like you/I do by fixing AdiBags architecture and I'll update this pull request when it's achieved.

**Comment by Meivyn** [comment]
I think my edits are done, let me know what you think of it. I fixed (I hope) all border stuff, but you may want to check if your code is still useful with my edits as I dropped it:
```lua
if self.IconQuestTexture:GetBlendMode() == "ADD" then
	if self.texture then -- Fix for free space button border when rebuying items with a border!
		self:SetBackdropBorderColor(self.IconQuestTexture:GetVertexColor())
	else
		self:SetBackdropBorderColor(0, 0, 0, 0)
	end
	self.IconQuestTexture:Hide()
else
	if self.texture and addon.db.profile.allHighlight then
		self:SetBackdropBorderColor(1, 1, 1)
	end
	self.IconQuestTexture:Show()
end
```

**Comment by Meivyn** [comment]
I mean now I'm done. I noticed some typos and I'm missing the ``allHighlight`` setting for junk, but I need to sleep now. Will see tomorrow.

**Comment by Meivyn** [comment]
But do you want it to be highlighted at all?

**Comment by Klixxx** [comment]
What should be highlighted?
And the icon position border issues is still there, ill have to look at it when i have more time.

**Comment by Meivyn** [comment]
You added an option to highlight all non-quality items, I missed the junk items in my edits.
And what issue are you talking about? There is still an issue when you switch item over another item, but when items are "moving" it should not. Like when you click on the bags icon, the layout is modified, and when you click back, borders was messed up. This is what I fixed.

**Comment by Klixxx** [comment]
Oh that issue i never had tho, when pressing the bag icon and the items in the repective bags were moved etc.
Only when changing icon position with an item with a border. 

Its fine junk items isnt highligthed, they are already dimmed by default

**Comment by Klixxx** [comment]
hit me up at discord, easier talking there Klix#1645

**Pull request merged**
