### PR TITLE
Shadowlands Prepatch 9.0.1 working version

### PR DESCRIPTION
**Pull request by gammarax**
Copied the changes made at https://github.com/AdiAddons/AdiBags/pull/477, currently works for prepatch

### CODE REVIEW

**Comment by xanahopper** [comment]
Nicely done!
Hope maintainer merge this asap

**Comment by xanahopper** [comment]
@Klixxx will this addon update at curse recently?

**Comment by Klixxx** [comment]
@xanahopper Later today hopefully :)

**Comment by Meivyn** [comment]
These changes are not nicely done at all, I'd consider pushing this commit https://github.com/AdiAddons/AdiBags/commit/1e437c099e5a6b4a9463ce8613349abc00779b12 instead.

**Comment by Klixxx** [comment]
@Meivyn 
Can you make a PR? I dont have a computer atm...

**Pull request merged**
